name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          *This release includes the latest changes and improvements.*
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.get_version.outputs.version }}...HEAD
          
          ### Installation
          
          Download the appropriate binary for your system below and see the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for setup instructions.
        draft: false
        prerelease: false

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-suffix: ""
            asset-name: "hypr-showkey-linux-x86_64"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary-suffix: ""
            asset-name: "hypr-showkey-linux-x86_64-musl"
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-suffix: ""
            asset-name: "hypr-showkey-macos-x86_64"
          - os: macos-latest
            target: aarch64-apple-darwin
            binary-suffix: ""
            asset-name: "hypr-showkey-macos-aarch64"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-suffix: ".exe"
            asset-name: "hypr-showkey-windows-x86_64.exe"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install musl tools (Linux musl only)
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.target }}-release-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Strip binary (Unix only)
      if: matrix.os != 'windows-latest'
      run: strip target/${{ matrix.target }}/release/hypr-showkey${{ matrix.binary-suffix }}

    - name: Create release package
      run: |
        mkdir -p release-package
        cp target/${{ matrix.target }}/release/hypr-showkey${{ matrix.binary-suffix }} release-package/
        cp README.md release-package/
        cp LICENSE release-package/
        cp showkey.yaml release-package/showkey.example.yaml

    - name: Create tarball (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd release-package
        tar -czf ../${{ matrix.asset-name }}.tar.gz *

    - name: Create zip (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd release-package
        7z a ../${{ matrix.asset-name }}.zip *

    - name: Upload Release Asset (Unix)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./${{ matrix.asset-name }}.tar.gz
        asset_name: ${{ matrix.asset-name }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./${{ matrix.asset-name }}.zip
        asset_name: ${{ matrix.asset-name }}.zip
        asset_content_type: application/zip